name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - uses: actions/cache@v3
      name: Cache venv
      with:
        path: ./.venv
        key: venv-${{ hashFiles('uv.lock') }}
    - name: run tests
      run: uv run pytest
